version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
      - DB_URL=${DB_URL}
    ports:
      - "${PORT}:4000"